import type { DiscoverItem, PinLabel } from './types';

/** ~20 realistic Chicago items for the discover feed */
export const MOCK_DISCOVER_ITEMS: DiscoverItem[] = [
  // ─── Restaurants (7) ───
  {
    id: 'mock-portillos',
    entityType: 'place',
    name: "Portillo's Hot Dogs",
    lat: 41.8935,
    lng: -87.6368,
    category: 'food_drink',
    subcategory: 'Hot Dogs',
    description: 'Legendary Chicago-style hot dogs, Italian beef, and chocolate cake shakes since 1963.',
    imageUrl: null,
    neighborhood: 'River North',
    rating: 4.5,
    priceRange: '$',
    tags: ['hot dogs', 'italian beef', 'fast casual', 'iconic'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.portillos.com',
  },
  {
    id: 'mock-lou-malnatis',
    entityType: 'place',
    name: "Lou Malnati's Pizzeria",
    lat: 41.8903,
    lng: -87.6339,
    category: 'food_drink',
    subcategory: 'Pizza',
    description: 'Famous deep-dish pizza with a buttery crust, a Chicago institution since 1971.',
    imageUrl: null,
    neighborhood: 'River North',
    rating: 4.6,
    priceRange: '$$',
    tags: ['deep dish', 'pizza', 'classic chicago'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.loumalnatis.com',
  },
  {
    id: 'mock-girl-goat',
    entityType: 'place',
    name: 'Girl & The Goat',
    lat: 41.8843,
    lng: -87.6483,
    category: 'food_drink',
    subcategory: 'New American',
    description: "Stephanie Izard's flagship restaurant with bold, globally-inspired shared plates.",
    imageUrl: null,
    neighborhood: 'West Loop',
    rating: 4.7,
    priceRange: '$$$',
    tags: ['fine dining', 'shared plates', 'celebrity chef'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.girlandthegoat.com',
  },
  {
    id: 'mock-alinea',
    entityType: 'place',
    name: 'Alinea',
    lat: 41.9138,
    lng: -87.6483,
    category: 'food_drink',
    subcategory: 'Molecular Gastronomy',
    description: 'Three-Michelin-star restaurant redefining fine dining with avant-garde techniques.',
    imageUrl: null,
    neighborhood: 'Lincoln Park',
    rating: 4.9,
    priceRange: '$$$$',
    tags: ['michelin', 'fine dining', 'tasting menu', 'molecular'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.alinearestaurant.com',
  },
  {
    id: 'mock-big-star',
    entityType: 'place',
    name: 'Big Star',
    lat: 41.9098,
    lng: -87.6772,
    category: 'food_drink',
    subcategory: 'Tacos',
    description: 'Honky-tonk taqueria with killer tacos, bourbon, and a legendary patio.',
    imageUrl: null,
    neighborhood: 'Wicker Park',
    rating: 4.4,
    priceRange: '$$',
    tags: ['tacos', 'patio', 'bourbon', 'late night'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.bigstarchicago.com',
  },
  {
    id: 'mock-frontera',
    entityType: 'place',
    name: 'Frontera Grill',
    lat: 41.8905,
    lng: -87.6310,
    category: 'food_drink',
    subcategory: 'Mexican',
    description: "Rick Bayless's pioneering Mexican cuisine using locally-sourced ingredients.",
    imageUrl: null,
    neighborhood: 'River North',
    rating: 4.5,
    priceRange: '$$$',
    tags: ['mexican', 'celebrity chef', 'farm to table'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.fronteragrill.net',
  },
  {
    id: 'mock-pequods',
    entityType: 'place',
    name: "Pequod's Pizza",
    lat: 41.9217,
    lng: -87.6645,
    category: 'food_drink',
    subcategory: 'Pizza',
    description: 'Cult-favorite pan pizza with a caramelized cheese crust that puts deep dish to shame.',
    imageUrl: null,
    neighborhood: 'Lincoln Park',
    rating: 4.7,
    priceRange: '$$',
    tags: ['pizza', 'caramelized crust', 'local favorite'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.pequodspizza.com',
  },

  // ─── Events (6) ───
  {
    id: 'mock-lolla',
    entityType: 'event',
    name: 'Lollapalooza 2026',
    lat: 41.8758,
    lng: -87.6189,
    category: null,
    subcategory: 'Music Festival',
    description: 'Four-day music festival featuring 170+ acts across 9 stages in Grant Park.',
    imageUrl: null,
    neighborhood: 'Grant Park',
    rating: null,
    priceRange: null,
    tags: ['music', 'festival', 'outdoor', 'multi-day'],
    startsAt: '2026-07-30T11:00:00',
    endsAt: '2026-08-02T22:00:00',
    venueName: 'Grant Park',
    attendingCount: 100000,
    websiteUrl: 'https://www.lollapalooza.com',
  },
  {
    id: 'mock-jazz-fest',
    entityType: 'event',
    name: 'Chicago Jazz Festival',
    lat: 41.8825,
    lng: -87.6221,
    category: null,
    subcategory: 'Music Festival',
    description: 'Free annual celebration of jazz with world-class musicians in Millennium Park.',
    imageUrl: null,
    neighborhood: 'Loop',
    rating: null,
    priceRange: null,
    tags: ['jazz', 'free', 'outdoor', 'music'],
    startsAt: '2026-08-28T17:00:00',
    endsAt: '2026-08-30T21:00:00',
    venueName: 'Millennium Park',
    attendingCount: 50000,
    websiteUrl: null,
  },
  {
    id: 'mock-second-city',
    entityType: 'event',
    name: 'Second City Comedy Show',
    lat: 41.9114,
    lng: -87.6345,
    category: null,
    subcategory: 'Comedy',
    description: 'Legendary improv comedy at the theater that launched countless SNL careers.',
    imageUrl: null,
    neighborhood: 'Old Town',
    rating: null,
    priceRange: null,
    tags: ['comedy', 'improv', 'theater', 'nightlife'],
    startsAt: '2026-03-15T20:00:00',
    endsAt: '2026-03-15T22:00:00',
    venueName: 'The Second City',
    attendingCount: 300,
    websiteUrl: 'https://www.secondcity.com',
  },
  {
    id: 'mock-arch-tour',
    entityType: 'event',
    name: 'Architecture River Cruise',
    lat: 41.8887,
    lng: -87.6240,
    category: null,
    subcategory: 'Tour',
    description: "Iconic boat tour along the Chicago River showcasing the city's architectural gems.",
    imageUrl: null,
    neighborhood: 'Loop',
    rating: null,
    priceRange: null,
    tags: ['architecture', 'tour', 'boat', 'sightseeing'],
    startsAt: '2026-03-20T10:00:00',
    endsAt: '2026-03-20T11:30:00',
    venueName: 'Chicago Riverwalk',
    attendingCount: 80,
    websiteUrl: null,
  },
  {
    id: 'mock-taste',
    entityType: 'event',
    name: 'Taste of Chicago',
    lat: 41.8765,
    lng: -87.6200,
    category: null,
    subcategory: 'Food Festival',
    description: "The world's largest outdoor food festival showcasing Chicago's diverse culinary scene.",
    imageUrl: null,
    neighborhood: 'Grant Park',
    rating: null,
    priceRange: null,
    tags: ['food', 'festival', 'outdoor', 'family'],
    startsAt: '2026-07-08T11:00:00',
    endsAt: '2026-07-12T21:00:00',
    venueName: 'Grant Park',
    attendingCount: 200000,
    websiteUrl: null,
  },
  {
    id: 'mock-blues-fest',
    entityType: 'event',
    name: 'Chicago Blues Festival',
    lat: 41.8825,
    lng: -87.6226,
    category: null,
    subcategory: 'Music Festival',
    description: "Free celebration of blues music in Millennium Park, honoring Chicago's blues heritage.",
    imageUrl: null,
    neighborhood: 'Loop',
    rating: null,
    priceRange: null,
    tags: ['blues', 'music', 'free', 'outdoor'],
    startsAt: '2026-06-12T11:00:00',
    endsAt: '2026-06-14T21:00:00',
    venueName: 'Millennium Park',
    attendingCount: 75000,
    websiteUrl: null,
  },

  // ─── Landmarks (5) ───
  {
    id: 'mock-bean',
    entityType: 'place',
    name: 'Cloud Gate (The Bean)',
    lat: 41.8827,
    lng: -87.6233,
    category: 'other',
    subcategory: 'Landmark',
    description: "Anish Kapoor's iconic reflective sculpture in Millennium Park — the ultimate selfie spot.",
    imageUrl: null,
    neighborhood: 'Loop',
    rating: 4.8,
    priceRange: null,
    tags: ['landmark', 'free', 'iconic', 'photo op'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: null,
  },
  {
    id: 'mock-art-institute',
    entityType: 'place',
    name: 'Art Institute of Chicago',
    lat: 41.8796,
    lng: -87.6237,
    category: 'other',
    subcategory: 'Museum',
    description: "World-class museum housing iconic works from Monet's haystacks to Grant Wood's Gothic.",
    imageUrl: null,
    neighborhood: 'Loop',
    rating: 4.9,
    priceRange: '$$',
    tags: ['museum', 'art', 'world class', 'impressionism'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.artic.edu',
  },
  {
    id: 'mock-willis',
    entityType: 'place',
    name: 'Willis Tower Skydeck',
    lat: 41.8789,
    lng: -87.6359,
    category: 'other',
    subcategory: 'Observation Deck',
    description: 'Step onto the glass Ledge 1,353 feet above Chicago for breathtaking views.',
    imageUrl: null,
    neighborhood: 'Loop',
    rating: 4.6,
    priceRange: '$$',
    tags: ['skyline', 'views', 'observation', 'iconic'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://theskydeck.com',
  },
  {
    id: 'mock-navy-pier',
    entityType: 'place',
    name: 'Navy Pier',
    lat: 41.8917,
    lng: -87.6063,
    category: 'other',
    subcategory: 'Entertainment',
    description: 'Lakefront landmark with rides, restaurants, boat tours, and fireworks.',
    imageUrl: null,
    neighborhood: 'Streeterville',
    rating: 4.3,
    priceRange: '$',
    tags: ['pier', 'rides', 'family', 'lakefront', 'fireworks'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://navypier.org',
  },
  {
    id: 'mock-wrigley',
    entityType: 'place',
    name: 'Wrigley Field',
    lat: 41.9484,
    lng: -87.6553,
    category: 'other',
    subcategory: 'Stadium',
    description: 'The Friendly Confines — home of the Chicago Cubs since 1914.',
    imageUrl: null,
    neighborhood: 'Wrigleyville',
    rating: 4.7,
    priceRange: '$$',
    tags: ['baseball', 'sports', 'historic', 'cubs'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.mlb.com/cubs',
  },

  // ─── Activities (3) ───
  {
    id: 'mock-kayak',
    entityType: 'place',
    name: 'Chicago River Kayaking',
    lat: 41.8869,
    lng: -87.6235,
    category: 'outdoors',
    subcategory: 'Water Sports',
    description: "Paddle through downtown Chicago's stunning architecture from river level.",
    imageUrl: null,
    neighborhood: 'Loop',
    rating: 4.8,
    priceRange: '$$',
    tags: ['kayak', 'river', 'outdoors', 'adventure'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: null,
  },
  {
    id: 'mock-606',
    entityType: 'place',
    name: 'The 606 Trail',
    lat: 41.9139,
    lng: -87.6842,
    category: 'outdoors',
    subcategory: 'Trail',
    description: "Elevated 2.7-mile trail connecting four neighborhoods — Chicago's High Line.",
    imageUrl: null,
    neighborhood: 'Bucktown',
    rating: 4.6,
    priceRange: null,
    tags: ['trail', 'biking', 'running', 'elevated', 'free'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: null,
  },
  {
    id: 'mock-lpz',
    entityType: 'place',
    name: 'Lincoln Park Zoo',
    lat: 41.9211,
    lng: -87.6340,
    category: 'outdoors',
    subcategory: 'Zoo',
    description: 'Free admission zoo in the heart of Lincoln Park — one of the oldest in the country.',
    imageUrl: null,
    neighborhood: 'Lincoln Park',
    rating: 4.5,
    priceRange: null,
    tags: ['zoo', 'free', 'family', 'animals', 'park'],
    startsAt: null,
    endsAt: null,
    venueName: null,
    attendingCount: null,
    websiteUrl: 'https://www.lpzoo.org',
  },
];

/** Derive an Airbnb-style pill label for a discover item */
export function getPinLabel(item: DiscoverItem): PinLabel {
  if (item.entityType === 'event' && item.startsAt) {
    const d = new Date(item.startsAt);
    const month = d.toLocaleString('en-US', { month: 'short' });
    const day = d.getDate();
    return { text: `${month} ${day}`, type: 'date' };
  }
  if (item.priceRange) {
    return { text: item.priceRange, type: 'price' };
  }
  if (item.rating) {
    return { text: item.rating.toFixed(1), type: 'rating' };
  }
  return { text: '★', type: 'rating' };
}
