/** Simple list of Chicago neighborhood names for the Filters dropdown */
export const CHICAGO_NEIGHBORHOOD_NAMES: string[] = [
    'Albany Park',
    'Andersonville',
    'Archer Heights',
    'Armour Square',
    'Ashburn',
    'Auburn Gresham',
    'Austin',
    'Avalon Park',
    'Avondale',
    'Back of the Yards',
    'Beverly',
    'Bowmanville',
    'Boystown',
    'Bridgeport',
    'Brighton Park',
    'Bronzeville',
    'Bucktown',
    'Burnside',
    'Calumet Heights',
    'Chatham',
    'Chicago Lawn',
    'Chinatown',
    'Clearing',
    'Douglas',
    'Dunning',
    'East Garfield Park',
    'East Side',
    'Edgewater',
    'Englewood',
    'Ford City',
    'Fulton Market',
    'Gage Park',
    'Galewood',
    'Garfield Ridge',
    'Gold Coast',
    'Grand Boulevard',
    'Grant Park',
    'Greater Grand Crossing',
    'Greektown',
    'Hegewisch',
    'Hermosa',
    'Humboldt Park',
    'Hyde Park',
    'Irving Park',
    'Jefferson Park',
    'Kenwood',
    'Lakeview',
    'Lincoln Park',
    'Lincoln Square',
    'Little Italy',
    'Little Village',
    'Logan Square',
    'Loop',
    'Lower West Side',
    'Magnificent Mile',
    'Marquette Park',
    'McKinley Park',
    'Montclare',
    'Morgan Park',
    'Mount Greenwood',
    'Near North Side',
    'Near South Side',
    'Near West Side',
    'North Center',
    'North Lawndale',
    'North Park',
    'Norwood Park',
    'Oakland',
    'Old Town',
    'Pilsen',
    'Portage Park',
    "Printer's Row",
    'Pullman',
    'Ravenswood',
    'River North',
    'Rogers Park',
    'Roscoe Village',
    'Roseland',
    'South Chicago',
    'South Deering',
    'South Loop',
    'South Shore',
    'Streeterville',
    'Ukrainian Village',
    'Uptown',
    'Washington Heights',
    'Washington Park',
    'West Elsdon',
    'West Garfield Park',
    'West Lawn',
    'West Loop',
    'West Pullman',
    'West Ridge',
    'West Town',
    'Wicker Park',
    'Woodlawn',
    'Wrigleyville',
];
